'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, BadgeCheck, Banknote, Battery, Check, ChevronDown, Clock3, Crosshair, Filter, Hammer, MapPin, Menu, PackageCheck, Search, ShieldCheck, ShoppingBag, Store, UserRound, Wrench, X, Zap } from 'lucide-react'

type Product = { name: string; brand: string; price: string; joule: string; age: string; drive: string; image: string; tag: string; stock: string }
const products: Product[] = [
  { name: 'HK416 A5 Sportline', brand: 'Umarex', price: '249,90 €', joule: '1,4 J', age: 'FSK 18', drive: 'S-AEG', image: 'https://images.unsplash.com/photo-1595590424283-b8f17842773f?auto=format&fit=crop&w=900&q=90', tag: 'Bestseller', stock: 'Sofort lieferbar' },
  { name: 'Hi-Capa 5.1 Match', brand: 'Tokyo Marui', price: '189,00 €', joule: '0,9 J', age: 'FSK 18', drive: 'GBB', image: 'https://images.unsplash.com/photo-1584285659284-2f4b2c02e34f?auto=format&fit=crop&w=900&q=90', tag: 'Neuheit', stock: 'Auf Lager' },
  { name: 'M4 CQB-R Gen. 2', brand: 'Specna Arms', price: '219,90 €', joule: '0,5 J', age: 'FSK 14', drive: 'S-AEG', image: 'https://images.unsplash.com/photo-1588099768523-f4e6a6b48f27?auto=format&fit=crop&w=900&q=90', tag: 'FSK 14', stock: 'Abholung Hanau' },
  { name: 'VSR-10 Pro Sniper', brand: 'Action Army', price: '159,90 €', joule: '1,8 J', age: 'FSK 18', drive: 'Federdruck', image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=90', tag: 'Top bewertet', stock: 'Sofort lieferbar' },
]
const categories = [
  ['Langwaffen', 'S-AEG · HPA · Bolt-Action', 'https://images.unsplash.com/photo-1595590424283-b8f17842773f?auto=format&fit=crop&w=1000&q=90'],
  ['Kurzwaffen', 'GBB · AEP · CO₂', 'https://images.unsplash.com/photo-1584285659284-2f4b2c02e34f?auto=format&fit=crop&w=1000&q=90'],
  ['Tactical Gear', 'Schutz · Tragesysteme · Zubehör', 'https://images.unsplash.com/photo-1521405924368-64c5b84bec60?auto=format&fit=crop&w=1000&q=90'],
  ['BBs & Energie', 'Präzisions-BBs · Gas · Akkus', 'https://images.unsplash.com/photo-1558980664-10ea2e25f49b?auto=format&fit=crop&w=1000&q=90'],
]

export default function Home() {
  const [cart, setCart] = useState<Product[]>([]); const [cartOpen, setCartOpen] = useState(false); const [ageOpen, setAgeOpen] = useState(false); const [menuOpen, setMenuOpen] = useState(false); const [query, setQuery] = useState(''); const [filterOpen, setFilterOpen] = useState(false)
  const filtered = useMemo(() => products.filter(p => `${p.name} ${p.brand} ${p.drive}`.toLowerCase().includes(query.toLowerCase())), [query])
  const add = (p: Product) => { setCart(c => [...c, p]); setCartOpen(true) }
  const total = cart.reduce((sum, p) => sum + Number(p.price.replace('.', '').replace(',', '.').replace(' €', '')), 0)
  return <main className="min-h-screen bg-[#09090b] text-zinc-100">
    <div className="border-b border-white/10 bg-[#121215] px-4 py-2 text-center text-xs text-zinc-400">Lokaler Fachhandel &amp; Werkstatt in Hanau <span className="mx-2 text-orange-500">•</span> Click &amp; Collect verfügbar <span className="mx-2 text-orange-500">•</span> Diskreter FSK-geprüfter Versand mit DHL</div>
    <header className="sticky top-4 z-40 mx-3 mt-3 rounded-2xl border border-white/10 bg-[#09090b]/80 backdrop-blur-xl shadow-2xl lg:mx-auto lg:max-w-6xl"><div className="flex items-center gap-4 px-4 py-3 lg:px-5">
      <button aria-label="Menü öffnen" className="relative grid size-9 place-items-center lg:hidden" onClick={() => setMenuOpen(!menuOpen)}><span className={`hamburger ${menuOpen ? 'is-open' : ''}`}><i /><i /><i /></span></button>
      <a href="#top" className="flex items-center gap-2.5"><span className="grid size-9 place-items-center rounded-lg bg-orange-500 text-black"><Crosshair size={21} /></span><span className="leading-none"><b className="block text-sm tracking-[.18em]">HANAU</b><small className="text-[10px] text-orange-400">AIRSOFT / TACTICAL GEAR</small></span></a>
      <nav className={`${menuOpen ? 'mobile-menu' : 'hidden'} lg:flex lg:items-center lg:gap-5 lg:static lg:ml-5 lg:bg-transparent lg:p-0`}>{['Langwaffen','Kurzwaffen','Airsoft ab 14','BBs & Gas','Tactical Gear','Store & Werkstatt'].map(i => <a key={i} href={i === 'Store & Werkstatt' ? '#store' : '#produkte'} onClick={() => setMenuOpen(false)}>{i}</a>)}<div className="mt-5 border-t border-white/10 pt-4 lg:hidden"><a href="tel:+496181123456">Store Hanau anrufen</a><a href="#store">Öffnungszeiten</a><a href="#cart" onClick={() => { setCartOpen(true); setMenuOpen(false) }}>Warenkorb ({cart.length})</a></div></nav>
      <div className="ml-auto flex items-center gap-3"><div className="hidden h-10 items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 md:flex"><Search size={16} className="text-zinc-500" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Produkte suchen..." className="w-44 bg-transparent text-sm outline-none placeholder:text-zinc-600" /></div><button aria-label="Konto" className="hidden text-zinc-400 hover:text-orange-400 sm:block"><UserRound size={19} /></button><button onClick={() => setCartOpen(true)} aria-label="Warenkorb öffnen" className="relative text-zinc-300 hover:text-orange-400"><ShoppingBag size={20} />{cart.length > 0 && <span className="absolute -right-2 -top-2 grid size-4 place-items-center rounded-full bg-orange-500 text-[10px] font-bold text-black">{cart.length}</span>}</button></div>
    </div></header>
    <section id="top" className="relative overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_35%,rgba(249,115,22,.13),transparent_32%),linear-gradient(180deg,#09090b,#121215 65%,#09090b)]" /><div className="relative mx-auto grid max-w-6xl items-center gap-12 px-5 pb-20 pt-24 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-28"><div><p className="eyebrow">Seit 2011 · Hanau, Rhein-Main</p><h1 className="mt-5 max-w-2xl text-5xl font-semibold tracking-[-.055em] text-white sm:text-7xl">Präzision,<br /><span className="text-orange-500">Leidenschaft</span><br />&amp; Expertise.</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-zinc-400">Dein Airsoft-Fachgeschäft im Rhein-Main-Gebiet. Ausgewählte Ausrüstung, persönliche Beratung und eine eigene Werkstatt – direkt vor Ort in Hanau.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#produkte" className="shine inline-flex items-center gap-2 rounded-xl bg-orange-500 px-5 py-3.5 text-sm font-semibold text-black">Katalog entdecken <ArrowRight size={17} /></a><a href="#store" className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/5 px-5 py-3.5 text-sm font-semibold hover:border-orange-500/60">Store &amp; Werkstatt <MapPin size={16} /></a></div></div><div className="relative hidden lg:block"><div className="hero-image overflow-hidden rounded-3xl border border-white/10 bg-[#18181b] p-3"><img src="https://images.unsplash.com/photo-1595590424283-b8f17842773f?auto=format&fit=crop&w=1100&q=90" alt="Airsoft Ausrüstung im Studio" className="h-[410px] w-full rounded-2xl object-cover" /></div><div className="absolute -bottom-5 -left-5 rounded-2xl border border-white/10 bg-[#18181b]/95 p-4 shadow-xl"><div className="flex items-center gap-2 text-sm font-semibold"><span className="size-2 rounded-full bg-orange-500" /> Fachberatung vor Ort</div><p className="mt-1 text-xs text-zinc-500">Store &amp; Werkstatt Hanau</p></div></div></div></section>
    <section className="border-y border-white/10 bg-[#121215]"><div className="mx-auto grid max-w-6xl grid-cols-2 sm:grid-cols-4">{[['Geprüfte Qualität', BadgeCheck],['Eigene Werkstatt', Wrench],['Sicherer Versand', PackageCheck],['Erfahrene Beratung', ShieldCheck]].map(([t, I]) => <div key={t as string} className="flex items-center gap-3 border-white/10 px-4 py-5 sm:border-r lg:px-6"><span className="text-orange-500"><I size={20} /></span><span className="text-sm font-medium text-zinc-200">{t as string}</span></div>)}</div></section>
    <section id="katalog" className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><div className="mb-8 flex items-end justify-between"><div><p className="eyebrow">Sortiment</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Für jedes Spielfeld.</h2></div><a href="#produkte" className="hidden items-center gap-2 text-sm font-semibold text-orange-400 sm:flex">Alle Kategorien <ArrowRight size={16} /></a></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map(([title, sub, image], i) => <a href="#produkte" key={title} className={`category-card group relative min-h-64 overflow-hidden rounded-2xl border border-white/10 bg-[#18181b] ${i === 0 ? 'sm:row-span-2 sm:min-h-[528px]' : ''}`}><img src={image} alt={title} className="absolute inset-0 size-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent" /><div className="relative flex h-full min-h-64 flex-col justify-end p-5"><span className="text-xs font-semibold text-orange-400">0{i + 1}</span><h3 className="mt-2 text-xl font-semibold">{title}</h3><p className="mt-1 text-sm text-zinc-400">{sub}</p><ArrowRight size={18} className="mt-5 text-zinc-400 transition group-hover:translate-x-1 group-hover:text-orange-400" /></div></a>)}</div></section>
    <section id="produkte" className="bg-gradient-to-b from-[#09090b] via-[#121215] to-[#09090b] py-20"><div className="mx-auto max-w-6xl px-5 lg:px-8"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Ausgewählt für dich</p><h2 className="mt-3 text-3xl font-semibold sm:text-4xl">Bestseller &amp; Neuheiten</h2></div><div className="flex items-center gap-2"><button onClick={() => setFilterOpen(!filterOpen)} className="flex items-center gap-2 rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm text-zinc-300 hover:border-orange-500/50"><Filter size={15} /> Filter <ChevronDown size={14} /></button><span className="text-sm text-zinc-500">{filtered.length} Produkte</span></div></div>{filterOpen && <div className="mb-6 grid gap-4 rounded-2xl border border-white/10 bg-[#18181b] p-5 text-sm sm:grid-cols-3"><FilterGroup title="Altersfreigabe" items={['FSK 14 (<0,5 J)','FSK 18 (ab 0,5 J)']} /><FilterGroup title="Antriebsart" items={['S-AEG','Gas / CO₂ Blowback','Federdruck','HPA']} /><FilterGroup title="Hersteller" items={['Umarex','Tokyo Marui','Specna Arms']} /></div>}<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{filtered.map(p => <ProductCard key={p.name} product={p} onAdd={() => add(p)} />)}</div></div></section>
    <section id="store" className="mx-auto grid max-w-6xl gap-10 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><p className="eyebrow">Nicht nur online</p><h2 className="mt-3 text-4xl font-semibold leading-tight">Komm vorbei.<br /><span className="text-orange-500">Wir sind für dich da.</span></h2><p className="mt-6 max-w-lg leading-relaxed text-zinc-400">Anfassen, ausprobieren, beraten lassen. Unser Store in Hanau verbindet Fachhandel mit einer voll ausgestatteten Werkstatt.</p><div className="mt-8 grid gap-5 sm:grid-cols-2"><Info icon={MapPin} title="Adresse" text={'Rodenbacher Chaussee 8\n63457 Hanau'} /><Info icon={Clock3} title="Öffnungszeiten" text={'Di–Fr 10:00–18:30 Uhr\nSa 10:00–16:00 Uhr'} /><Info icon={Store} title="Click & Collect" text="Ausweisprüfung bei Abholung" /><Info icon={Hammer} title="Werkstatt" text="Tuning · Wartung · Reparatur" /></div></div><div className="grid min-h-[380px] place-items-center rounded-3xl border border-white/10 bg-[linear-gradient(135deg,#18181b,#0f0f12)] p-8 text-center"><div><MapPin size={42} className="mx-auto text-orange-500" /><p className="eyebrow mt-5">Dein Weg zu uns</p><h3 className="mt-3 text-2xl font-semibold">Store &amp; Werkstatt Hanau</h3><p className="mt-3 text-sm text-zinc-500">Parkplätze direkt vor dem Laden. Google Maps Ansicht folgt.</p><a href="#" className="mt-7 inline-flex rounded-xl border border-white/15 px-5 py-3 text-sm font-semibold hover:border-orange-500">Route planen <ArrowRight size={16} className="ml-2" /></a></div></div></section>
    <footer className="border-t border-white/10 bg-[#121215]"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-12 sm:grid-cols-2 lg:grid-cols-4 lg:px-8"><div><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-orange-500 text-black"><Crosshair size={17} /></span><b className="tracking-[.15em]">HANAU</b></div><p className="mt-4 text-sm leading-relaxed text-zinc-500">Airsoft, Tactical Gear und professioneller Service im Rhein-Main-Gebiet.</p></div><FooterCol title="Service" links={['Kontakt','Store & Werkstatt','Click & Collect','Versand & Lieferung']} /><FooterCol title="Rechtliches" links={['Impressum','AGB','Datenschutz','Widerrufsbelehrung']} /><FooterCol title="Hinweise" links={['Batteriegesetz','Elektroaltgeräte','Altersnachweis','Sicher transportieren']} /></div><div className="border-t border-white/10 px-5 py-5 text-center text-xs text-zinc-600">© 2024 Hanau Airsoft / Tactical Gear · Sicher bezahlen · DHL Alterssichtprüfung</div></footer>
    {cartOpen && <Cart cart={cart} setCart={setCart} total={total} close={() => setCartOpen(false)} checkout={() => setAgeOpen(true)} />}{ageOpen && <AgeModal close={() => setAgeOpen(false)} />}
  </main>
}

function ProductCard({ product, onAdd }: { product: Product; onAdd: () => void }) { return <article className="group overflow-hidden rounded-2xl border border-white/10 bg-[#18181b] shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-white/20 hover:shadow-xl"><div className="relative aspect-[1.1] overflow-hidden bg-zinc-100 p-3"><img src={product.image} alt={product.name} className="size-full object-cover rounded-xl transition duration-500 group-hover:scale-105" /><span className="absolute left-5 top-5 rounded-full bg-orange-500 px-2.5 py-1 text-xs font-semibold text-black">{product.tag}</span><span className="absolute right-5 top-5 rounded-full border border-zinc-300 bg-white px-2.5 py-1 text-xs font-semibold text-zinc-800">{product.age}</span></div><div className="p-5"><p className="text-sm font-medium text-orange-400">{product.brand}</p><h3 className="mt-1 text-lg font-semibold text-white">{product.name}</h3><div className="mt-3 flex items-center gap-2 text-xs text-zinc-400"><span className="rounded-full bg-white/10 px-2.5 py-1">{product.drive}</span><span className="rounded-full bg-white/10 px-2.5 py-1">{product.joule}</span></div><div className="mt-5 flex items-end justify-between gap-3"><div><p className="text-xl font-semibold">{product.price}</p><p className="mt-1 text-xs text-emerald-400">● {product.stock}</p></div><button onClick={onAdd} className="rounded-xl bg-orange-500 px-3 py-2 text-sm font-semibold text-black hover:bg-orange-400"><ShoppingBag size={16} /></button></div></div></article> }
function FilterGroup({ title, items }: { title: string; items: string[] }) { return <div><p className="mb-3 font-semibold text-white">{title}</p>{items.map(i => <label key={i} className="mb-2 flex items-center gap-2 text-zinc-400"><input type="checkbox" className="accent-orange-500" />{i}</label>)}</div> }
function Info({ icon: Icon, title, text }: { icon: typeof MapPin; title: string; text: string }) { return <div className="flex gap-3"><Icon size={19} className="mt-0.5 shrink-0 text-orange-500" /><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 whitespace-pre-line text-sm leading-relaxed text-zinc-500">{text}</p></div></div> }
function FooterCol({ title, links }: { title: string; links: string[] }) { return <div><h3 className="text-sm font-semibold text-orange-400">{title}</h3><div className="mt-4 space-y-3">{links.map(l => <a key={l} href="#" className="block text-sm text-zinc-500 hover:text-white">{l}</a>)}</div></div> }
function Cart({ cart, setCart, total, close, checkout }: { cart: Product[]; setCart: (c: Product[]) => void; total: number; close: () => void; checkout: () => void }) { return <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm" onClick={close}><aside onClick={e => e.stopPropagation()} className="absolute right-0 top-0 flex h-full w-full max-w-md flex-col border-l border-white/10 bg-[#121215] shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 p-5"><div><p className="eyebrow">Deine Auswahl</p><h2 className="mt-1 text-xl font-semibold">Warenkorb ({cart.length})</h2></div><button onClick={close} aria-label="Warenkorb schließen"><X /></button></div><div className="flex-1 overflow-y-auto p-5">{cart.length ? cart.map((p, i) => <div key={`${p.name}-${i}`} className="flex gap-3 border-b border-white/10 py-4"><img src={p.image} alt="" className="size-20 rounded-lg object-cover" /><div className="flex-1"><p className="text-sm font-semibold">{p.name}</p><p className="mt-2 text-sm text-zinc-400">{p.price}</p></div><button onClick={() => setCart(cart.filter((_, n) => n !== i))} aria-label="Artikel entfernen"><X size={15} /></button></div>) : <div className="grid h-full place-items-center text-zinc-500"><ShoppingBag size={38} /></div>}</div>{cart.length > 0 && <div className="border-t border-white/10 p-5"><div className="mb-4 flex gap-3 rounded-xl border border-orange-500/30 bg-orange-500/10 p-3 text-xs leading-relaxed text-orange-200"><ShieldCheck size={17} className="shrink-0" /> FSK 18 Artikel im Warenkorb. Bitte halte deinen Personalausweis bereit.</div><div className="mb-4 flex justify-between text-sm"><span className="text-zinc-500">Zwischensumme</span><b>{total.toFixed(2).replace('.', ',')} €</b></div><button onClick={checkout} className="w-full rounded-xl bg-orange-500 py-3.5 text-sm font-semibold text-black">Zur Kasse</button></div>}</aside></div> }
function AgeModal({ close }: { close: () => void }) { return <div className="fixed inset-0 z-[60] grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl border border-orange-500/30 bg-[#18181b] p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between"><div className="grid size-12 place-items-center rounded-full bg-orange-500/15 text-orange-500"><ShieldCheck /></div><button onClick={close} aria-label="Dialog schließen"><X size={20} /></button></div><p className="eyebrow mt-7">Altersprüfung erforderlich</p><h2 className="mt-2 text-2xl font-semibold">Frei ab 18 Jahren</h2><p className="mt-4 text-sm leading-relaxed text-zinc-400">Beim Versand erfolgt die Identitätsprüfung durch DHL. Bei Click &amp; Collect prüfen wir deinen Ausweis direkt im Store.</p><div className="mt-6 space-y-3 rounded-xl border border-white/10 bg-white/5 p-4 text-sm text-zinc-300"><div className="flex gap-2"><Check size={16} className="text-orange-500" /> Volljährigkeit bestätigen</div><div className="flex gap-2"><Check size={16} className="text-orange-500" /> Ausweis beim Empfang bereithalten</div></div><button onClick={close} className="mt-6 w-full rounded-xl bg-orange-500 py-3.5 text-sm font-semibold text-black">Verstanden, weiter zur Kasse</button></div></div> }
